// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: daily_insight.
// - Entity ID: 102019af65e1c81754b9029f3d8931c0fa4.
// - Entity Version: 102019af6e7ad6870d497a83f57b7e1c51d.
// - Task ID: 6934f343afa64bd4a96b337f.
// - Task Root ID: 6934d32689dfb99c8f5f08b3.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for DailyInsightCategory
 */
export enum DailyInsightCategory {
  Unspecified = 0,
  Spending = 1,
  Saving = 2,
  Budget = 3,
  General = 4,
}



/**
 * Interface for DailyInsightModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface DailyInsightModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  insight_date: string;
  insight_text: string;
  category: DailyInsightCategory;
}

/**
 * ORM class for DailyInsight entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class DailyInsightORM {
  private static instance: DailyInsightORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019af65e1c81754b9029f3d8931c0fa4';
    this.entityName = 'daily_insight';
    this.entityVersion = '102019af6e7ad6870d497a83f57b7e1c51d';
    this.taskId = '6934f343afa64bd4a96b337f';
    this.taskRootId = '6934d32689dfb99c8f5f08b3';
  }

  /**
   * Get singleton instance of DailyInsightORM
   */
  public static getInstance(): DailyInsightORM {
    if (!DailyInsightORM.instance) {
      DailyInsightORM.instance = new DailyInsightORM();
    }
    
    return DailyInsightORM.instance;
  }

  /**
   * Get all DailyInsight records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllDailyInsight(): Promise<DailyInsightModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new DailyInsight record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertDailyInsight(data: DailyInsightModel[]): Promise<DailyInsightModel[]> {
    const structured = data.map((item) => CreateData(DailyInsightModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all DailyInsight records
   */
  async purgeAllDailyInsight(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List DailyInsight records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listDailyInsight(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[DailyInsightModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get daily_insight by Id index
   * This function gets data by index.
   */
  async getDailyInsightById(
    id: string,
  ): Promise<DailyInsightModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_insight by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyInsightById(
    id: string,
    data: DailyInsightModel
  ): Promise<DailyInsightModel[]> {
    const index = createIndexId(
      id
    );

    const values = DailyInsightModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_insight by Id index
   */
  async deleteDailyInsightById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_insight by UserId index
   * This function gets data by index.
   */
  async getDailyInsightByUserId(
    user_id: string,
  ): Promise<DailyInsightModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_insight by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyInsightByUserId(
    user_id: string,
    data: DailyInsightModel
  ): Promise<DailyInsightModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = DailyInsightModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_insight by UserId index
   */
  async deleteDailyInsightByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_insight by InsightDate index
   * This function gets data by index.
   */
  async getDailyInsightByInsightDate(
    insight_date: string,
  ): Promise<DailyInsightModel[]> {
    const index = createIndexInsightDate(
      insight_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_insight by InsightDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyInsightByInsightDate(
    insight_date: string,
    data: DailyInsightModel
  ): Promise<DailyInsightModel[]> {
    const index = createIndexInsightDate(
      insight_date
    );

    const values = DailyInsightModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_insight by InsightDate index
   */
  async deleteDailyInsightByInsightDate(
    insight_date: string
  ): Promise<void> {
    const index = createIndexInsightDate(
      insight_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_insight by DataCreator index
   * This function gets data by index.
   */
  async getDailyInsightByDataCreator(
    data_creator: string,
  ): Promise<DailyInsightModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_insight by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyInsightByDataCreator(
    data_creator: string,
    data: DailyInsightModel
  ): Promise<DailyInsightModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = DailyInsightModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_insight by DataCreator index
   */
  async deleteDailyInsightByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get daily_insight by DataUpdater index
   * This function gets data by index.
   */
  async getDailyInsightByDataUpdater(
    data_updater: string,
  ): Promise<DailyInsightModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) daily_insight by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDailyInsightByDataUpdater(
    data_updater: string,
    data: DailyInsightModel
  ): Promise<DailyInsightModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = DailyInsightModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete daily_insight by DataUpdater index
   */
  async deleteDailyInsightByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to DailyInsightModel data array
   */
  private resultToData(values: Data[]): DailyInsightModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return DailyInsightModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as DailyInsightModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized DailyInsightModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is DailyInsightModel => item !== null);
  }
}

/**
 * Convert DailyInsightModel data to Value array
 */
function DailyInsightModelToValues(data: DailyInsightModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'insight_date', type: DataType.string, defaultValue: '' },
    { key: 'insight_text', type: DataType.string, defaultValue: '' },
    { key: 'category', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof DailyInsightModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to DailyInsightModel data
 */
function DailyInsightModelFromValues(values: Value[]): DailyInsightModel {
  const data: Partial<DailyInsightModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'insight_date':
        data.insight_date = ParseValue(value, DataType.string) as string;
        break;
      case 'insight_text':
        data.insight_text = ParseValue(value, DataType.string) as string;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.enumeration) as DailyInsightCategory;
        break;
    }
  }
  
  return data as DailyInsightModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for InsightDate fields
 */
function createIndexInsightDate(
  insight_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, insight_date, 'insight_date'),
  ];

  return {
    fields: ['insight_date'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default DailyInsightORM;