// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: transaction.
// - Entity ID: 102019af65e1c817bb48e54a06a222899b4.
// - Entity Version: 102019af6e7ad6870d497a83f57b7e1c51d.
// - Task ID: 6934f343afa64bd4a96b337f.
// - Task Root ID: 6934d32689dfb99c8f5f08b3.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for TransactionCategory
 */
export enum TransactionCategory {
  Unspecified = 0,
  Food = 1,
  Entertainment = 2,
  Transportation = 3,
  Utilities = 4,
  Shopping = 5,
  Health = 6,
  Subscriptions = 7,
  Other = 8,
}



/**
 * Interface for TransactionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TransactionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  amount: number;
  category: TransactionCategory;
  description?: string | null;
  transaction_time: string;
  is_recurring: boolean;
}

/**
 * ORM class for Transaction entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TransactionORM {
  private static instance: TransactionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019af65e1c817bb48e54a06a222899b4';
    this.entityName = 'transaction';
    this.entityVersion = '102019af6e7ad6870d497a83f57b7e1c51d';
    this.taskId = '6934f343afa64bd4a96b337f';
    this.taskRootId = '6934d32689dfb99c8f5f08b3';
  }

  /**
   * Get singleton instance of TransactionORM
   */
  public static getInstance(): TransactionORM {
    if (!TransactionORM.instance) {
      TransactionORM.instance = new TransactionORM();
    }
    
    return TransactionORM.instance;
  }

  /**
   * Get all Transaction records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTransaction(): Promise<TransactionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Transaction record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTransaction(data: TransactionModel[]): Promise<TransactionModel[]> {
    const structured = data.map((item) => CreateData(TransactionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Transaction records
   */
  async purgeAllTransaction(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Transaction records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTransaction(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TransactionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get transaction by Id index
   * This function gets data by index.
   */
  async getTransactionById(
    id: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionById(
    id: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexId(
      id
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by Id index
   */
  async deleteTransactionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by UserId index
   * This function gets data by index.
   */
  async getTransactionByUserId(
    user_id: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByUserId(
    user_id: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by UserId index
   */
  async deleteTransactionByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by TransactionTime index
   * This function gets data by index.
   */
  async getTransactionByTransactionTime(
    transaction_time: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexTransactionTime(
      transaction_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by TransactionTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByTransactionTime(
    transaction_time: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexTransactionTime(
      transaction_time
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by TransactionTime index
   */
  async deleteTransactionByTransactionTime(
    transaction_time: string
  ): Promise<void> {
    const index = createIndexTransactionTime(
      transaction_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by Category index
   * This function gets data by index.
   */
  async getTransactionByCategory(
    category: TransactionCategory,
  ): Promise<TransactionModel[]> {
    const index = createIndexCategory(
      category
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by Category index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByCategory(
    category: TransactionCategory,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexCategory(
      category
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by Category index
   */
  async deleteTransactionByCategory(
    category: TransactionCategory
  ): Promise<void> {
    const index = createIndexCategory(
      category
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by DataCreator index
   * This function gets data by index.
   */
  async getTransactionByDataCreator(
    data_creator: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByDataCreator(
    data_creator: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by DataCreator index
   */
  async deleteTransactionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by DataUpdater index
   * This function gets data by index.
   */
  async getTransactionByDataUpdater(
    data_updater: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByDataUpdater(
    data_updater: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by DataUpdater index
   */
  async deleteTransactionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TransactionModel data array
   */
  private resultToData(values: Data[]): TransactionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TransactionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TransactionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TransactionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TransactionModel => item !== null);
  }
}

/**
 * Convert TransactionModel data to Value array
 */
function TransactionModelToValues(data: TransactionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'amount', type: DataType.number, defaultValue: 0 },
    { key: 'category', type: DataType.enumeration, defaultValue: 0 },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'transaction_time', type: DataType.string, defaultValue: '' },
    { key: 'is_recurring', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TransactionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TransactionModel data
 */
function TransactionModelFromValues(values: Value[]): TransactionModel {
  const data: Partial<TransactionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'amount':
        data.amount = ParseValue(value, DataType.number) as number;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.enumeration) as TransactionCategory;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'transaction_time':
        data.transaction_time = ParseValue(value, DataType.string) as string;
        break;
      case 'is_recurring':
        data.is_recurring = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as TransactionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for TransactionTime fields
 */
function createIndexTransactionTime(
  transaction_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, transaction_time, 'transaction_time'),
  ];

  return {
    fields: ['transaction_time'],
    values
  };
}
/**
 * Create index for Category fields
 */
function createIndexCategory(
  category: TransactionCategory
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, category, 'category'),
  ];

  return {
    fields: ['category'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default TransactionORM;