// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: budget.
// - Entity ID: 102019af65e1c807a8ba2a50ee5b7b5a9ea.
// - Entity Version: 102019af6e7ad6870d497a83f57b7e1c51d.
// - Task ID: 6934f343afa64bd4a96b337f.
// - Task Root ID: 6934d32689dfb99c8f5f08b3.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for BudgetModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface BudgetModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  category_name: string;
  monthly_limit: number;
  current_spent: number;
  alert_threshold: number;
  is_active: boolean;
}

/**
 * ORM class for Budget entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class BudgetORM {
  private static instance: BudgetORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019af65e1c807a8ba2a50ee5b7b5a9ea';
    this.entityName = 'budget';
    this.entityVersion = '102019af6e7ad6870d497a83f57b7e1c51d';
    this.taskId = '6934f343afa64bd4a96b337f';
    this.taskRootId = '6934d32689dfb99c8f5f08b3';
  }

  /**
   * Get singleton instance of BudgetORM
   */
  public static getInstance(): BudgetORM {
    if (!BudgetORM.instance) {
      BudgetORM.instance = new BudgetORM();
    }
    
    return BudgetORM.instance;
  }

  /**
   * Get all Budget records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllBudget(): Promise<BudgetModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Budget record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertBudget(data: BudgetModel[]): Promise<BudgetModel[]> {
    const structured = data.map((item) => CreateData(BudgetModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Budget records
   */
  async purgeAllBudget(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Budget records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listBudget(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[BudgetModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get budget by Id index
   * This function gets data by index.
   */
  async getBudgetById(
    id: string,
  ): Promise<BudgetModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) budget by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBudgetById(
    id: string,
    data: BudgetModel
  ): Promise<BudgetModel[]> {
    const index = createIndexId(
      id
    );

    const values = BudgetModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete budget by Id index
   */
  async deleteBudgetById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get budget by UserId index
   * This function gets data by index.
   */
  async getBudgetByUserId(
    user_id: string,
  ): Promise<BudgetModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) budget by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBudgetByUserId(
    user_id: string,
    data: BudgetModel
  ): Promise<BudgetModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = BudgetModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete budget by UserId index
   */
  async deleteBudgetByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get budget by DataCreator index
   * This function gets data by index.
   */
  async getBudgetByDataCreator(
    data_creator: string,
  ): Promise<BudgetModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) budget by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBudgetByDataCreator(
    data_creator: string,
    data: BudgetModel
  ): Promise<BudgetModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = BudgetModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete budget by DataCreator index
   */
  async deleteBudgetByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get budget by DataUpdater index
   * This function gets data by index.
   */
  async getBudgetByDataUpdater(
    data_updater: string,
  ): Promise<BudgetModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) budget by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBudgetByDataUpdater(
    data_updater: string,
    data: BudgetModel
  ): Promise<BudgetModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = BudgetModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete budget by DataUpdater index
   */
  async deleteBudgetByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to BudgetModel data array
   */
  private resultToData(values: Data[]): BudgetModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return BudgetModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as BudgetModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized BudgetModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is BudgetModel => item !== null);
  }
}

/**
 * Convert BudgetModel data to Value array
 */
function BudgetModelToValues(data: BudgetModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'category_name', type: DataType.string, defaultValue: '' },
    { key: 'monthly_limit', type: DataType.number, defaultValue: 0 },
    { key: 'current_spent', type: DataType.number, defaultValue: 0 },
    { key: 'alert_threshold', type: DataType.number, defaultValue: 0 },
    { key: 'is_active', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof BudgetModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to BudgetModel data
 */
function BudgetModelFromValues(values: Value[]): BudgetModel {
  const data: Partial<BudgetModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'category_name':
        data.category_name = ParseValue(value, DataType.string) as string;
        break;
      case 'monthly_limit':
        data.monthly_limit = ParseValue(value, DataType.number) as number;
        break;
      case 'current_spent':
        data.current_spent = ParseValue(value, DataType.number) as number;
        break;
      case 'alert_threshold':
        data.alert_threshold = ParseValue(value, DataType.number) as number;
        break;
      case 'is_active':
        data.is_active = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as BudgetModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default BudgetORM;