// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: subscription.
// - Entity ID: 102019af65e1c8171b3961310eaa510310d.
// - Entity Version: 102019af6e7ad6870d497a83f57b7e1c51d.
// - Task ID: 6934f343afa64bd4a96b337f.
// - Task Root ID: 6934d32689dfb99c8f5f08b3.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for SubscriptionBillingCycle
 */
export enum SubscriptionBillingCycle {
  Unspecified = 0,
  Monthly = 1,
  Yearly = 2,
  Weekly = 3,
}



/**
 * Interface for SubscriptionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface SubscriptionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  service_name: string;
  amount: number;
  billing_cycle: SubscriptionBillingCycle;
  next_billing_date: string;
  category: string;
  cancellation_url?: string | null;
  is_active: boolean;
}

/**
 * ORM class for Subscription entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class SubscriptionORM {
  private static instance: SubscriptionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019af65e1c8171b3961310eaa510310d';
    this.entityName = 'subscription';
    this.entityVersion = '102019af6e7ad6870d497a83f57b7e1c51d';
    this.taskId = '6934f343afa64bd4a96b337f';
    this.taskRootId = '6934d32689dfb99c8f5f08b3';
  }

  /**
   * Get singleton instance of SubscriptionORM
   */
  public static getInstance(): SubscriptionORM {
    if (!SubscriptionORM.instance) {
      SubscriptionORM.instance = new SubscriptionORM();
    }
    
    return SubscriptionORM.instance;
  }

  /**
   * Get all Subscription records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllSubscription(): Promise<SubscriptionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Subscription record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertSubscription(data: SubscriptionModel[]): Promise<SubscriptionModel[]> {
    const structured = data.map((item) => CreateData(SubscriptionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Subscription records
   */
  async purgeAllSubscription(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Subscription records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listSubscription(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[SubscriptionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get subscription by Id index
   * This function gets data by index.
   */
  async getSubscriptionById(
    id: string,
  ): Promise<SubscriptionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) subscription by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSubscriptionById(
    id: string,
    data: SubscriptionModel
  ): Promise<SubscriptionModel[]> {
    const index = createIndexId(
      id
    );

    const values = SubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete subscription by Id index
   */
  async deleteSubscriptionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get subscription by UserId index
   * This function gets data by index.
   */
  async getSubscriptionByUserId(
    user_id: string,
  ): Promise<SubscriptionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) subscription by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSubscriptionByUserId(
    user_id: string,
    data: SubscriptionModel
  ): Promise<SubscriptionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = SubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete subscription by UserId index
   */
  async deleteSubscriptionByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get subscription by DataCreator index
   * This function gets data by index.
   */
  async getSubscriptionByDataCreator(
    data_creator: string,
  ): Promise<SubscriptionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) subscription by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSubscriptionByDataCreator(
    data_creator: string,
    data: SubscriptionModel
  ): Promise<SubscriptionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = SubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete subscription by DataCreator index
   */
  async deleteSubscriptionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get subscription by DataUpdater index
   * This function gets data by index.
   */
  async getSubscriptionByDataUpdater(
    data_updater: string,
  ): Promise<SubscriptionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) subscription by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSubscriptionByDataUpdater(
    data_updater: string,
    data: SubscriptionModel
  ): Promise<SubscriptionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = SubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete subscription by DataUpdater index
   */
  async deleteSubscriptionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to SubscriptionModel data array
   */
  private resultToData(values: Data[]): SubscriptionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return SubscriptionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as SubscriptionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized SubscriptionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is SubscriptionModel => item !== null);
  }
}

/**
 * Convert SubscriptionModel data to Value array
 */
function SubscriptionModelToValues(data: SubscriptionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'service_name', type: DataType.string, defaultValue: '' },
    { key: 'amount', type: DataType.number, defaultValue: 0 },
    { key: 'billing_cycle', type: DataType.enumeration, defaultValue: 0 },
    { key: 'next_billing_date', type: DataType.string, defaultValue: '' },
    { key: 'category', type: DataType.string, defaultValue: '' },
    { key: 'cancellation_url', type: DataType.string, defaultValue: null },
    { key: 'is_active', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof SubscriptionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to SubscriptionModel data
 */
function SubscriptionModelFromValues(values: Value[]): SubscriptionModel {
  const data: Partial<SubscriptionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'service_name':
        data.service_name = ParseValue(value, DataType.string) as string;
        break;
      case 'amount':
        data.amount = ParseValue(value, DataType.number) as number;
        break;
      case 'billing_cycle':
        data.billing_cycle = ParseValue(value, DataType.enumeration) as SubscriptionBillingCycle;
        break;
      case 'next_billing_date':
        data.next_billing_date = ParseValue(value, DataType.string) as string;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.string) as string;
        break;
      case 'cancellation_url':
        data.cancellation_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'is_active':
        data.is_active = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as SubscriptionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default SubscriptionORM;