// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: savings_goal.
// - Entity ID: 102019af65e1c807df689a10be55be19e9e.
// - Entity Version: 102019af6e7ad6870d497a83f57b7e1c51d.
// - Task ID: 6934f343afa64bd4a96b337f.
// - Task Root ID: 6934d32689dfb99c8f5f08b3.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for SavingsGoalModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface SavingsGoalModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  goal_name: string;
  target_amount: number;
  current_amount: number;
  deadline?: string | null;
  priority_level: number;
  is_completed: boolean;
}

/**
 * ORM class for SavingsGoal entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class SavingsGoalORM {
  private static instance: SavingsGoalORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019af65e1c807df689a10be55be19e9e';
    this.entityName = 'savings_goal';
    this.entityVersion = '102019af6e7ad6870d497a83f57b7e1c51d';
    this.taskId = '6934f343afa64bd4a96b337f';
    this.taskRootId = '6934d32689dfb99c8f5f08b3';
  }

  /**
   * Get singleton instance of SavingsGoalORM
   */
  public static getInstance(): SavingsGoalORM {
    if (!SavingsGoalORM.instance) {
      SavingsGoalORM.instance = new SavingsGoalORM();
    }
    
    return SavingsGoalORM.instance;
  }

  /**
   * Get all SavingsGoal records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllSavingsGoal(): Promise<SavingsGoalModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new SavingsGoal record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertSavingsGoal(data: SavingsGoalModel[]): Promise<SavingsGoalModel[]> {
    const structured = data.map((item) => CreateData(SavingsGoalModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all SavingsGoal records
   */
  async purgeAllSavingsGoal(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List SavingsGoal records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listSavingsGoal(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[SavingsGoalModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get savings_goal by Id index
   * This function gets data by index.
   */
  async getSavingsGoalById(
    id: string,
  ): Promise<SavingsGoalModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) savings_goal by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSavingsGoalById(
    id: string,
    data: SavingsGoalModel
  ): Promise<SavingsGoalModel[]> {
    const index = createIndexId(
      id
    );

    const values = SavingsGoalModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete savings_goal by Id index
   */
  async deleteSavingsGoalById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get savings_goal by UserId index
   * This function gets data by index.
   */
  async getSavingsGoalByUserId(
    user_id: string,
  ): Promise<SavingsGoalModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) savings_goal by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSavingsGoalByUserId(
    user_id: string,
    data: SavingsGoalModel
  ): Promise<SavingsGoalModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = SavingsGoalModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete savings_goal by UserId index
   */
  async deleteSavingsGoalByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get savings_goal by DataCreator index
   * This function gets data by index.
   */
  async getSavingsGoalByDataCreator(
    data_creator: string,
  ): Promise<SavingsGoalModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) savings_goal by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSavingsGoalByDataCreator(
    data_creator: string,
    data: SavingsGoalModel
  ): Promise<SavingsGoalModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = SavingsGoalModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete savings_goal by DataCreator index
   */
  async deleteSavingsGoalByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get savings_goal by DataUpdater index
   * This function gets data by index.
   */
  async getSavingsGoalByDataUpdater(
    data_updater: string,
  ): Promise<SavingsGoalModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) savings_goal by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSavingsGoalByDataUpdater(
    data_updater: string,
    data: SavingsGoalModel
  ): Promise<SavingsGoalModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = SavingsGoalModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete savings_goal by DataUpdater index
   */
  async deleteSavingsGoalByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to SavingsGoalModel data array
   */
  private resultToData(values: Data[]): SavingsGoalModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return SavingsGoalModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as SavingsGoalModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized SavingsGoalModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is SavingsGoalModel => item !== null);
  }
}

/**
 * Convert SavingsGoalModel data to Value array
 */
function SavingsGoalModelToValues(data: SavingsGoalModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'goal_name', type: DataType.string, defaultValue: '' },
    { key: 'target_amount', type: DataType.number, defaultValue: 0 },
    { key: 'current_amount', type: DataType.number, defaultValue: 0 },
    { key: 'deadline', type: DataType.string, defaultValue: null },
    { key: 'priority_level', type: DataType.number, defaultValue: 0 },
    { key: 'is_completed', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof SavingsGoalModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to SavingsGoalModel data
 */
function SavingsGoalModelFromValues(values: Value[]): SavingsGoalModel {
  const data: Partial<SavingsGoalModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'goal_name':
        data.goal_name = ParseValue(value, DataType.string) as string;
        break;
      case 'target_amount':
        data.target_amount = ParseValue(value, DataType.number) as number;
        break;
      case 'current_amount':
        data.current_amount = ParseValue(value, DataType.number) as number;
        break;
      case 'deadline':
        data.deadline = ParseValue(value, DataType.string) as string | null;
        break;
      case 'priority_level':
        data.priority_level = ParseValue(value, DataType.number) as number;
        break;
      case 'is_completed':
        data.is_completed = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as SavingsGoalModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default SavingsGoalORM;